repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--skip-string-normalization"]
        exclude: ^app/infra/db/migrations/

  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        name: Run flake8
        exclude: ^app/infra/db/migrations/versions