services:
  db:
    container_name: 'task-manager-db'
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=taskmanager

  db-test:
    container_name: 'task-manager-db-test'
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=taskmanager_test