name: Run E2E Tests

on: [ pull_request ]

jobs:
  run-e2e-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/postgresql
        ports:
          - 5433:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: taskmanager_test

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -v -s app/tests/http/
        env:
          ENVIRONMENT: test
          SECRET_KEY: testing
          DATABASE_URL: "postgresql+asyncpg://docker:docker@localhost:5432/taskmanager"
          DATABASE_URL_TEST: "postgresql+asyncpg://docker:docker@localhost:5433/taskmanager_test"
          EMAIL_HOST: 'test-email-host'
          EMAIL_PORT: '465'
          EMAIL_HOST_USER: 'test-email-user'
          EMAIL_HOST_PASSWORD: 'test-email-password'
          BROKER_HOST: 'test-broker-host'
          BROKER_PORT: 6379