name: Run E2E Tests

on: [ push ]

jobs:
  run-e2e-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: taskmanager_test

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest -v -s app/tests/use_cases/
        env:
          ENVIRONMENT: test
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/taskmanager"
          DATABASE_URL_TEST: "postgresql://docker:docker@localhost:5432/taskmanager_test"